datasets:
    task_gen:
        _name: task_gen
        samples_per_class: [1000, 200]
        concept_pool:
#            _name: mnist_tree
            _name: synthetic_tree
        transformation_pool:
#            _name: randperm_x_transformation
#            _name: nn_x_transformation
            _name: rot_x_transformation
        strat:
            _name: transfo
#            _name: random

modules:
    ll_models:
        ER:
            _name: er
        single:
            _name: singlehead
        multihead:
            _name: multihead
        ewc:
            _name: ewc
        inde:
            _name: independent

optimizers:
    optim:
        _name: adam
        _modules: [ewc, ER, multihead, single, inde]

experiment:
    _name: lifelong_exp
    cuda: true
    train: True
    n_epochs: 5
    n_tasks: 25

    patience: 50
    visdom_traces_folder: 'traces'
    batch_sizes: [64, 1024]  # Train and Eval batch sizes

    log_steps: [1, 2, 3, 4, 5, 7, 10, 20, 30, 50, 100, 500, 1000]
    auc_Ks: [1, 3, 5, 10, 30, 50, 100, 500, 1000]
    log_epoch: True
    normalize_auc: True

    plot_tasks: True


#seed: 1