datasets:
    task_gen:
        _name: task_gen
        samples_per_class: [-1, 200, 200]
        split_names: ['Train', 'Val', 'Test']

        concept_pool:
            _name: cifar10_tree
            n_classes: 10

        transformation_pool:
            _name: img_rot_x_transformation

        strat:
            _name: transfo
            n_initial_classes: 10

modules:
    ll_models:
        _name: all-models-resnet-dict

optimizers:
    optim:
        _name: adam
        _modules: []

experiment:
    _name: lifelong_exp

    n_it_max: 4000
    grace_period: 500

    n_tasks: 50
    log_steps: [1, 2, 3, 4, 5]
    norm_models: [0-0-0-0-0-0-inde, inde-upper-bound]

    patience: 500

#seed: 1