global_exp : &global
    cuda: True

lifelong_exp:
    log_dir: /checkpoint/ranzato/ray_results
    smoke_test: false

    name: ll
    cuda: true
    use_ray: true
    use_ray_logging: False
    redis_address: 'localhost:6382'
    use_threads: True
    local_mode: False
    n_it_max: 5000
    grace_period: 1500
    num_hp_samplings: 1
    resources:
        cpu: 2
        gpu: 0.25

    n_tasks: 50

    patience: 100
    visdom_traces_folder: /checkpoint/ranzato/visdom_traces
    batch_sizes: [64, 1024]  # Train and Eval batch sizes
    norm_models: [0-0-0-inde, inde-upper-bound]

    log_steps: [1, 2, 3, 4, 5]
    log_epoch: False

    task_save_folder: /checkpoint/ranzato/datasets

    plot_tasks: False

