datasets:
    task_gen:
        _name: task_gen
        samples_per_class: [5000, 200, 200]
        split_names: ['Train', 'Val', 'Test']

        concept_pool:
#            _name: mnist_tree
            _name: synthetic_tree
            scale_fact: 0.7
            cov_scale: 0.15
        transformation_pool:
#            _name: randperm_x_transformation
#            _name: nn_x_transformation
            _name: noisy_nn_x_transformation
#            _name: rot_x_transformation
        strat:
            _name: transfo
#            n_initial_classes: 27
#            _name: random

modules:
    ll_models:
      _name: all-models-dict

optimizers:
    optim:
        _name: adam
        _modules: []

experiment:
    _name: lifelong_exp

    n_it_max: 5000
    grace_period: 1500

    n_tasks: 50

    patience: 500

#seed: 1
