datasets:
    task_gen:
        _name: task_gen
        samples_per_class: [5, 200, 200]
        split_names: ['Train', 'Val', 'Test']

        concept_pool:
#            _name: mnist_tree
            _name: synthetic_tree
            n_attrs: 1000

#            scale_fact: 0.7
#            cov_scale: 0.15
        transformation_pool:
#            _name: randperm_x_transformation
#            _name: nn_x_transformation
            _name: noisy_nn_x_transformation
            n_canonic_transfo: 50
            n_var_per_trans: 20
#            _name: rot_x_transformation
        strat:
            _name: mixed
                domain: xyz
                strategies:
                    x:
                        _name: transfo
                        n_initial_classes: 2
                    y:
                        _name: attributes
                        resample_classes: true
                        n_initial_classes: 27
                    z:
                        _name: split
                        n_initial_classes: 2
                        reuse_attrs: false
                        exclusive: False

modules:
    ll_models:
      _name: all-models-dict

optimizers:
    optim:
        _name: adam
        _modules: []

experiment:
    _name: lifelong_exp
    name: 1k

    n_it_max: 3000
    grace_period: 500

    n_tasks: 1000
    log_steps: [1, 2, 3, 4, 5]

    patience: 500

#seed: 1